name: Manual

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Manual run tags'
        required: false
        type: boolean

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./android
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
      with:
        path: ./android
        submodules: recursive

    - name: set up JDK 12
      uses: actions/setup-java@v2
      with:
        java-version: '12'
        distribution: 'adopt'

    - name: Download aar
      run: ./downloadAar.sh

    - name: Check aar exists
      run: test -f "libwebrtc.aar"

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Create gpg key and import into gradle properties
      run: |
        echo $GPG_KEY_ARMOR | base64 --decode > ./release.asc
        gpg --quiet --output $GITHUB_WORKSPACE/release.gpg --dearmor ./release.asc
        sed -i -e "s,mavenCentralUsername=,mavenCentralUsername=$NEXUS_USERNAME,g" gradle.properties
        sed -i -e "s,mavenCentralPassword=,mavenCentralPassword=$NEXUS_PASSWORD,g" gradle.properties
        sed -i -e "s,signing.keyId=,signing.keyId=$GPG_KEY_ID,g" gradle.properties
        sed -i -e "s,signing.password=,signing.password=$GPG_PASSWORD,g" gradle.properties
        sed -i -e "s,signing.secretKeyRingFile=,signing.secretKeyRingFile=$GITHUB_WORKSPACE/release.gpg,g" gradle.properties
      env:
        GPG_KEY_ARMOR: ${{ secrets.SIGNING_KEY_ARMOR }}
        GPG_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
        GPG_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

    - name: Publish to sonatype
      run: ./gradlew publishToMavenCentral --no-configuration-cache
